export const GET_DATA_REQUEST="GET_DATA_REQUEST";
export const GET_DATA_SUCCESS="GET_DATA_SUCCESS";
export const GET_DATA_FAILURE="GET_DATA_FAILURE";

 export const POST_DATA_REQUEST="POST_DATA_REQUEST";
 export const POST_DATA_SUCCESS="POST_DATA_SUCCESS";
 export const POST_DATA_FAILURE="POST_DATA_FAILURE";

// ACCEPT POST PART
export const ACCEPT_POST_DATA_REQUEST="ACCEPT_POST_DATA_REQUEST";
export const ACCEPT_POST_DATA_SUCCESS="ACCEPT_POST_DATA_SUCCESS";
export const ACCEPT_POST_DATA_FAILURE="ACCEPT_POST_DATA_FAILURE";
// ACCEPT GET PART
export const ACCEPT_GET_DATA_REQUEST="ACCEPT_GET_DATA_REQUEST";
export const ACCEPT_GET_DATA_SUCCESS="ACCEPT_GET_DATA_SUCCESS";
export const ACCEPT_GET_DATA_FAILURE="ACCEPT_GET_DATA_FAILURE";





// REJECTED POST PART
export const REJECTED_POST_DATA_REQUEST="REJECTED_POST_DATA_REQUEST";
export const REJECTED_POST_DATA_SUCCESS="REJECTED_POST_DATA_SUCCESS";
export const REJECTED_POST_DATA_FAILURE="REJECTED_POST_DATA_FAILURE";
// REJECTED GET PART
export const REJECTED_GET_DATA_REQUEST="REJECTED_GET_DATA_REQUEST";
export const REJECTED_GET_DATA_SUCCESS="REJECTED_GET_DATA_SUCCESS";
export const REJECTED_GET_DATA_FAILURE="REJECTED_GET_DATA_FAILURE";
